const express = require("express")
const path = require("path")
const cors = require("cors")
// const blogRoute = require("./routes/blogRoutes")
const db = require("./config/db")
require("dotenv").config({ path: "./config/.env" })
db()
const app = express()

app.use(cors())
app.use(express.static("public"))
app.use(express.json())
app.use("/blog", require("./routes/blogRoutes"))
const PORT = process.env.PORT || 5000
app.listen(PORT, console.log(`server running on port ${PORT}`))